import {
    Vertical,
    BottomAppBar,
    NavigationBar,
    ElevatedCard,
    SegmentedButton,
    Horizontal,
    NavigationDrawer,
    ModalNavigationDrawer,
    FilledButton,
} from "material/material.slint";

export component App inherits Window {
    drawer := NavigationDrawer {
        height: parent.height;
        // width: parent.width * 0.5;
        groups: [
            {
                title: "Main",
                items: [
                    { icon: @image-url("lucide/file-play.svg"), text: "Home" },
                    { icon: @image-url("lucide/file-play.svg"), text: "Search" }
                ]
            }
        ];
    }

    content := Vertical {
        Rectangle {
            vertical-stretch: 1;
        }

        show_navigation_drawer := FilledButton {
            icon: @image-url("lucide/menu");
        }
    }
}
